language: python
python:
- '3.4'
install:
- pip install .
script:
- "./travistest.py"
env:
  global:
  - secure: U8FP+EzwxKskhk16sVHi8/ibny33LinzBbj7nWO/JtX6VABV5vvWOrEyUa14xfMkURQEF+EHq+iAUfSMPCQNbleVtgkh1X/y/TWaMozoTt/4HDvlvg4e7d8qL8dUyIv2HC0a2hQgLC6jdOdBzOTgrpSW2Lp5s2/STkEwvCRN+pyWy/xWoBTzdIhzH1wyJZF6M8AlelRqf7+I+8RTSw82KfJFi0DdnnieLxSFRJNiE9zEHPxqJluBqHBKpLo3U/+2S4ZtxGFKGnVl6yTTdjW8ETbMRZAPHYEqeYevwq5ROP7N28ywN98UGRikzHxg+EQkX/Mq5QiCFzAqNEXWKq3zLi/qQD1aLEsH+jEGLIrmoiQ9p4GGwhZX5PcK0DFOXx9kqasZ2gABKlxrq37q+pvHNyXFIAF7oQOXFOLYpWnC60Uge/docUyUjiQdlEgAJYf0Gmjn93C+q3XF22g7Ma7LXuz0enStSoN0FVeXkmgCUO8Ay6pVOWuiIg4ZS7GxzRBf8QaZBJLhWf0759GMWqldkIRy2jjna0gJFfi/mfBFYI8/jJ08nANQZOymqSydfNDBLj30RgTwz0ExpPv9oLl7OjmZZ8F8/k4rfYbUVt127TYMUfSPDCqpHix7o4teXlEe+w21h1Br0LuIttGqZXn7bROBM1RUZCeMbHOF1eCQRIg=
  - secure: b3gEKeZ8aWsJsZI/JP6g5AM3xxK8bKn7ZIfR0FbT9xitwevTagoXSguD2JjXXUGeFgxVnM8fnSoHdwcZC16J//wXAafg8kEk+jv5NwJ/jZhOyJtTVV8E3CJ4vH0bDS5oDVn1uK2OiG7aelYukGUEH1tNrDNTJey7M0BEGIVwqDhh5UBZLU1nRXzDFAywG6/45yfxtsgNciRHZAxNfJU+Ak3hrdhXg6KUgIZ1n7t54NbkWd0o0EKQfjxodDQ+196VfmBF555Gpn13B/3FwE8AQcFB8beBGA/5KjeZozp4eDVf6KzCG92UEWRm4/jzocWPAimjVqykBEfu4gr2K5Jc/i3AFMtKlBBlHgTgX4QyzRlSbsy8S241Mnl5RIvhkyGvcDSq/A8tYyq/83BJNcFgE8Dervma7jsXQ0k2mA4Yf6pCvFMwvf+tzowFhX/fshMa7oDBPoU60Nqx4TgapwwcIWR0YnTDHVnAPWU7fX9xSfdkCdQUnKEagt2NMPK+Ai3X8HtRL2Lrcst5NyrehS2GXoEywuT5zLAHzzMcJ3/HlPrQUdkqT7dGBMqRw58jgdBRI/JyAJTigiafgQVKk411IK77PEuHiUHgH7AVSOqvMf01p4Z+4GFnaMNcw1qLCrJOZSzobDGmfLHX+u/MAy2Zd5SIyGQuY1SzPOfZTp5cj4w=
notifications:
  email: false
